{
 "title": "Smart Water",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "CO2 Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Dioxyde_de_carbone" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dioxyde de carbone CO2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Dioxyde de carbone CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Dioxyde_de_carbone" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "alias": "Status",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "BATTERY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luminosity Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Luminosity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luminosity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Luminosity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "BATTERY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.2)"
    }
   ]
  },
  {
   "title": "Humidity Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Humidity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Outside Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Dioxyde_de_carbone" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(apps.$app.$server.counters.requests.count, 2)"
    }
   ]
  },
  {
   "title": "Luminosity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Luminosity",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(apps.$app.$server.counters.requests.count, 2)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(apps.$app.$server.counters.requests.count, 2)"
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "repeat": "server",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(apps.$app.$server.counters.requests.count, 2)"
    }
   ]
  },
  {
   "title": "Outside Temperature / Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "celsius", "label": "Temp" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'temp_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Water_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'humi_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Dioxyde_de_carbone" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luminosity / pH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "celsius", "label": "Temp" }
   ],
   "targets": [
    {
     "alias": "Luminosity",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'temp_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'humi_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outside Temperature / Water Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "celsius", "label": "Outside Temp" }
   ],
   "targets": [
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'temp_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Outside_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Water Temperature",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'humi_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Water_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pH / Water Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "pH" }
   ],
   "targets": [
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'temp_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Water Temperature",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'humi_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Water_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pH Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "CO2 / Humidity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "celsius", "label": "Temp" }
   ],
   "targets": [
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'temp_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Dioxyde_de_carbone" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "Smart_Water",
     "query": "SELECT mean(\"value\") FROM \"wxt_value\" WHERE \"instance\" = '46.234.46.52-4001' AND \"type_instance\" = 'humi_air' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "Outside_Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conductivity Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Conductivity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Electrical_Conductivity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conductivity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Conductivity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Electrical_Conductivity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Water Temperature Index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Water Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Water_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Water Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Water_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Sensors Data",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
   "format": "timeseries_to_rows",
   "targets": [
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "raw_document"
      }
     ],
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(apps.backend.*.counters.requests.count, 2)",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outside Humidity",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Water Temperature",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Water_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Dioxyde_de_carbone" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Conductivity",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Electrical_Conductivity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Luminosity",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Luminosity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "Outside_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Status",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Smart_Water",
     "select": [
      [
       { "params": [ "BATTERY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}